# Escribe DATABASE_URL en .env (codifica la contraseña). No subas .env a git.
param(
    [string]$Host = "70.38.95.210",
    [int]$Port = 3306,
    [string]$User = "administrator_oya_app_admin",
    [string]$Password = "",
    [string]$Database = "administrator_oya-app",
    [string]$EnvFile = ""
)

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
if (-not $EnvFile) { $EnvFile = Join-Path $root ".env" }

if (-not $Password) {
    $sec = Read-Host "Password MySQL" -AsSecureString
    $bstr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($sec)
    $Password = [Runtime.InteropServices.Marshal]::PtrToStringAuto($bstr)
}

$encoded = python -c "from urllib.parse import quote_plus; import sys; print(quote_plus(sys.argv[1]))" $Password
if ($LASTEXITCODE -ne 0) { throw "Python required to encode password" }

$url = "mysql+pymysql://${User}:${encoded}@${Host}:${Port}/${Database}"

$lines = @()
if (Test-Path $EnvFile) {
    $replaced = $false
    Get-Content $EnvFile -Encoding UTF8 | ForEach-Object {
        if ($_ -match '^\s*DATABASE_URL\s*=') {
            $lines += "DATABASE_URL=$url"
            $script:replaced = $true
        } else {
            $lines += $_
        }
    }
    if (-not $replaced) { $lines += "DATABASE_URL=$url" }
} else {
    $lines = @(
        "# Generated by configure-mysql-env.ps1",
        "DATABASE_URL=$url",
        "SECRET_KEY=change-me-to-a-long-random-string",
        "ENVIRONMENT=production"
    )
}

$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($EnvFile, ($lines -join "`n") + "`n", $utf8NoBom)
Write-Host "Updated $EnvFile with DATABASE_URL (password encoded)."
Write-Host "Run: pip install -r requirements.txt; alembic upgrade head"
